<?php

namespace elseym\HKPeterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GpgKeyMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpgKeyMetadataRepository extends EntityRepository
{
}
