<?php

namespace elseym\HKPeterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GpgKeyUserIdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpgKeyUserIdRepository extends EntityRepository
{
}
